blog/urls.py
from django.urls import path
from . import views
app_name='blog'
urlpatterns = [
    path('all/',views.blog_list,name='list'),
    path('search/',views.post_search,name='search'),
    path('<int:id>/',views.blog_detail,name='detail'),
    path('new_post/',views.new_post,name='new'),
    path('<int:id>/update',views.update_post,name='update'),
    path('<int:id>/delete',views.delete_post,name='delete'),
    path('<int:id>/like',views.like,name='like'),
    path('<int:id>/likee',views.like_with_ajax,name='ajax')
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from froala_editor import views

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('admin/', admin.site.urls),
    path('',include('index.urls',namespace='index')),
    path('blog/',include('blog.urls',namespace='blog')),
    path('froala_editor/',include('froala_editor.urls')),
    path('contact/',include('contact.urls',namespace='contact')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from froala_editor.fields import FroalaField
from taggit.managers import TaggableManager
# Create your models here.
day=[('sat','sat'),
('sun','sun'),('mon','mon'),('tues','tues'),('wed','wed'),('thur','thur'),('fri','fri')]
class Post(models.Model):
    title=models.CharField(max_length=50,default='',unique=True)
    content=FroalaField()
    post_time=models.TimeField()
    post_day=models.CharField(max_length=5,choices=day,null=True,blank=True)
    post_date=models.DateField()
    tags=TaggableManager()
    view_count=''
    author=models.ForeignKey(User,related_name='post_author',on_delete=models.CASCADE)
    post_image=models.ImageField(upload_to='post_image/')
    like=models.ManyToManyField(User,related_name='user_like')
    add_to_favorite=models.ManyToManyField(User,related_name='user_favorities')
    def __str__(self):
        return self.title
class comments(models.Model):
    commented_post=models.ForeignKey(Post,to_field='title',related_name='post_comment',on_delete=models.CASCADE)
    author=models.ForeignKey(User,related_name='author',on_delete=models.CASCADE)
    comment_date=models.DateField(auto_now_add=True)
    content=models.TextField(max_length=500,null=True,blank=True)
    def __str__(self):
        return str(self.author)   
class reply(models.Model):
    reply_post=models.ForeignKey(comments,related_name='reply_post',null=True,blank=True,on_delete=models.CASCADE)
    reply_author=models.ForeignKey(User,related_name='reply_author',on_delete=models.CASCADE)
    reply_time=models.TimeField(auto_now=True)
    content=models.TextField(max_length=100,blank=True,null=True)
    def children(self):
        return reply.objects.filter(reply_post=comments)
    @property
    def is_parent(self):
        if self.is_parent is not None:
            return False
        return True

blog/forms.py
from django import forms
from .models import Post,comments,reply
class PostForm(forms.ModelForm):
    class Meta:                              
        model=Post
        fields='__all__'
class commentForm(forms.ModelForm):
    class Meta:
        model=comments
        fields= ['content']    
class replyform(forms.ModelForm):
    content=forms.CharField(widget=forms.Textarea(attrs={'rows':2}),label='')
    content=forms.CharField(widget=forms.TextInput(attrs={'placeholder':'add reply....'}))
    class Meta:
        model=reply
        fields=['content',]

blog/views.py
from django.shortcuts import redirect, render
from .models import Post , comments ,reply
from index.models import category,place
from taggit.models import Tag
from django.db.models import Q , Count
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import PostForm , commentForm , replyform
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
# Create your views here.
def blog_list(request):
    all_posts=Post.objects.all()
    categories=category.objects.all()
    address=place.objects.all()
    tags=Tag.objects.all()
    paginator = Paginator(all_posts, 3)
    page = request.GET.get('page')
    try:
        all_posts = paginator.page(page)
    except PageNotAnInteger:
        all_posts = paginator.page(1)
    except EmptyPage:
        all_posts = paginator.page(paginator.num_pages)
    last_posts = Post.objects.all().order_by('post_date')[:3]
    return render(request,'blog/blog_list.html',{'posts':all_posts,'categories':categories , 'address':address  ,'tags':tags , 'last_post':last_posts
     })
def post_search(request):
    search_name=request.GET.get('q')
    search_result=Post.objects.filter(
                Q(title__icontains=search_name) |
                Q(content__icontains=search_name)
    )
    categories=category.objects.all()
    address=place.objects.all()
    return render(request,'blog/blog_search.html',{'search_result':search_result , 'categories':categories , 'address':address})
def blog_detail(request,id):
    post1=Post.objects.get(id=id)
    print (post1)
    user=request.user
    print (request.user)
    #global comment_count
    #comment_count=comments.objects.filter(commented_post=post1)
    comment=comments.objects.all()
    if request.method=="POST":
        comment_form=commentForm(request.POST,request.FILES)
        if comment_form.is_valid():
            form=comment_form.save(commit=False)
            form.commented_post=post1
            #print(post1)
            form.author=user
            #print(user)
            form.save()
    else:
        comment_form=commentForm()
    if request.method=='POST':
        parent_id=request.POST.get('parent_id')
        print(parent_id)
        reply_form=replyform(request.POST,request.FILES)
        if reply_form.is_valid():
            parent_id=request.POST.get('parent_id')
            print(parent_id)
            if parent_id:
                parent_qs=comments.objects.filter(id=parent_id)
                print(parent_qs)
                if parent_qs.exists() and parent_qs.count()==1:
                    global parent_obj
                    parent_obj=parent_qs.first()
                    print(parent_obj)
            form2=reply_form.save(commit=False)
            form2.reply_author=user
            form2.reply_post=parent_obj
            form2.save()
            return redirect('blog:list')
    else:
        reply_form=replyform()
    return render(request,'blog/blog_detail.html', {'post':post1  , 'comment':comment , 'comment_form':comment_form , 'reply_form':reply_form})
def update_post(request,id):
    single_post=Post.objects.get(id=id)
    if request.method=='POST':
        postfore=PostForm(request.POST,request.FILES,instance=single_post)
        if postfore.is_valid():
            postfore.save()
    else:
        postfore=PostForm(instance=single_post)
    return render(request,'blog/update_post.html',{'postform':postfore})
@login_required
def new_post(request):
    if request.method=='POST':
        postform=PostForm(request.POST,request.FILES)
        if postform.is_valid():
            postform.save()
    else:
        postform=PostForm()
    return render(request,'blog/add_new_post.html',{'postform':postform})
def delete_post(request,id):
    single_post=Post.objects.get(id=id)
    single_post.delete()
    return redirect('index:index')
def like(request,id):
    single_post=Post.objects.get(id=id)
    if request.user in single_post.like.all():
        single_post.like.remove(request.user)
    else:
        single_post.like.add(request.user)
    return redirect('blog:list')
def like_with_ajax(request,id):
    single_post=Post.objects.get(id=id)
    if request.user in single_post.like.all():
        single_post.like.remove(request.user)
        like.value='unlike'
    else:
        single_post.like.add(request.user)
        like.value='like'
    data={
        'value':like.value,
        'likes':single_post.like.all().count()
    }
    return JsonResponse(data,safe=False)

blog/templates/blog/add_new_post.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{% block body %}
  

<div dir="rtl">
    <!-- Search -->
    <div class="catagory_area ">
<div class="container " style="margin-top: 10rem">
            <div class=" single_text">
                <h2>احجز مع
                    أفضل دكتور في مصر</h3>
                <h3>احجز اونلاين او كلم  ١٧٧٥۸</h4>
                <h4>١٦٠٠٠ دكتور -٤٠٠٠ استاذ واستشاري - اكثر من ۲٠ تخصص</h5>
                <br>
            </div>
            <form  method="GET" action="">
            <div class="row cat_search" >

                <div class="col-lg-3 col-md-4">
                    <div class="single_input">
                        <input type="text" placeholder="إسم الدكتور" >
                    </div>
                </div>

                <div class="col-lg-3 col-md-4">
                    <div class="single_input">
                        <select class="wide" >
                            <option value="" >الموقع</option>
                            <option value="المنصوره">المنصوره</option>
                            <option value="الدقي">الدقي</option>
                            <option value="4">Sylet</option>
                        </select>
                    </div>
                </div>

                <div class="col-lg-3 col-md-4">
                    <div class="single_input">
                        <select class="wide" >
                            <option value="">التخصص</option>
                            <option value="جلدية">جلدية</option>
                            <option value="اسنان">اسنان</option>
                            <option value="نفسي">نفسي</option>
                            <option value="اطفال">اطفال حديثي الولادة</option>
                            <option value="مخ">مخ واعصاب</option>
                            <option value="عظام">عظام</option>
                            <option value="نساء">نساء وتوليد</option>
                            <option value="انف">انف واذن وحنجرة</option>
                            <option value="قلب">قلب واوعية دموية</option>
                            <option value="امراض">امراض دم</option>
                            <option value="اورام">اورام</option>
                            <option value="باطنه">باطنه</option>
                            <option value="تخسيس">تخسيس وتغذية</option>
                            <option value="جاطفال">جراحة اطفال</option>
                            <option value="جاورام">جراحة اورام</option>
                            <option value="جاوعيه">جراحة اوعية دموية</option>
                            <option value="جتجميل">جراحة تجميل</option>
                            <option value="سمنه">جراحه سمنة ومناظير </option>
                            </select>
                    </div>
                </div>

                <div class="col-lg-3 col-md-12">
                    <div class="job_btn">
                        <input type="submit" class="boxed-btn3" value="ابحث هنا">
                    </div>
                </div>

            </div>
            </form> 
        </div>
    </div>
    <!-- endsearch -->

</div>
<!-- bradcam_area  -->

<div dir="rtl">
<div class="container">
    <div class="signup">

    <div class="col-md-9" >
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <h4 class="auth-header">انشاء مدونه جديده</h4>
            {% bootstrap_form postform %}
            <div class="buttons-w"><button type="submit" class="btn btn-success">اضافة</button></div>
            
        </form>
    </div>
    </div>
</div>
</div>

{% endblock body %}

blog/templates/blog/blog_list.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{% block body %}

<div dir="rtl">
    <!-- Search -->
    {% include "home/search.html" %}
    <!-- endsearch -->

</div>
<!-- bradcam_area  -->


<div class="bradcam_text ">
    <h3>مقالات طبيه</h3>
</div>

    <!--/ bradcam_area  -->
    <!--================Blog Area =================-->


    <section class="blog_area section-padding">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 " >
                    <div class="blog_right_sidebar">
                        <aside class="single_sidebar_widget search_widget">
                            <form method="GET" action="{% url 'blog:search' %}">
                                <div class="form-group">
                                    <div class="input-group mb-3">
                                        <input name='q' type="text" class="form-control" placeholder='بحث فى المقالات'
                                            onfocus="this.placeholder = ''"
                                            onblur="this.placeholder = 'Search Keyword'">
                                        <div class="input-group-append">
                                            <button class="btn" type="button"><i class="ti-search"></i></button>
                                        </div>
                                    </div>
                                </div>
                                <button class="button rounded-0 primary-bg text-white w-100 btn_1 boxed-btn"
                                    type="submit">إبحث</button>
                            </form>
                        </aside>
                        <aside class="single_sidebar_widget popular_post_widget">
                            <h3 class="widget_title">أقدم المقالات</h3>

                            {% for l_p in last_post %}
                              
                            
                            <div class="media post_item">
                                <img src="{{l_p.post_image.url}}" alt="" style="width: 30spx; height: 30px;">
                                <div class="media-body">
                                    <a href="single-blog.html">
                                        <h3>{{l_p.title}}</h3>
                                    </a>
                                    <p>published at: <span style="color: #00D363;">{{l_p.post_date}}</p>
                                </div>
                            </div>

                            {% endfor %}
                        </aside>
                    </div>
                </div>
                {% for post in posts %}
                <div class="col-lg-8 mb-5 mb-lg-0" >
                    <div class="blog_left_sidebar" >
                        <article class="blog_item">
                            <div class="blog_item_img">
                                <img class="card-img rounded-0" src="{{post.post_image.url}}" alt="">
                                <a href="{% url 'blog:detail' post.id %}" class="blog_item_date">
                                    <h3>{{post.post_time}}</h3>
                                    <p>{{post.post_day}}</p>
                                </a>
                            </div>

                            <div class="blog_details"> 
                                <a class="d-inline-block" href="{% url 'blog:detail' post.id %}">
                                    <h2>{{post.title}}</h2>
                                </a>
                                <p>{{post.content}}</p>
                                <ul class="blog-info-link">
                                    {% for tag in post.tags.all %}
                                    <li><a href="#"><i class="fa fa-user"></i> {{tag}}</a></li>
                                    {% endfor %}
                                    <li><a href="#"><i class="fa fa-comments"></i> {{post.post_comment.count}} Comments</a></li>
                                    <li><a href="#"><i class="fa fa-likes"></i> {{post.like.count}} like</a></li>
                                </ul>
                            </div>
                        </article>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>
    <!--================Blog Area =================-->
</div>
<nav class="blog-pagination justify-content-center d-flex">
    {% if posts.has_other_pages %}
    <ul class="pagination">
        {% if posts.has_previous %}
        <li class="page-item">
            <a href="?page={{ users.previous_page_number }}" class="page-link" aria-label="Previous">
                <i class="ti-angle-right"></i>
            </a>
        </li>
        {% else %}
        <li class="disabled" aria-label="Previous"><</li>
        {% endif %}
        {% for i in posts.paginator.page_range %}
        {% if posts.number == i %}

        <li class="page-item">
            <a href="" class="page-link">{{i}}</a>
        </li>
        {% else %}
        <li class="page-item active">
            <a href="?page={{ i }}" class="page-link">{{i}}</a>
        </li>
        {% endif %}
        {% endfor %}
        {% if posts.has_next %}

        <li class="page-item">
            <a href="?page={{ post.next_page_number }}" class="page-link" aria-label="Next">
                <i class="ti-angle-right"></i>
            </a>
        </li>
        {% else %}
        <li class="disabled" aria-label="Next">></li>
        {% endif %}

    </ul>
    {% endif %}
</nav>
{% endblock body %}

blog/templates/blog/blog_search.html
{% extends 'base.html' %}
{% load static %}
{% block body %}

<div dir="rtl">
    <!-- Search -->
    {% include "home/search.html" %}
    <!-- endsearch -->

</div>
<!-- bradcam_area  -->


<div class="bradcam_text ">
    <h3>مقالات طبيه</h3>
</div>

    <!--/ bradcam_area  -->
    <!--================Blog Area =================-->


    <section class="blog_area section-padding">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 " >
                    <div class="blog_right_sidebar">
                        <aside class="single_sidebar_widget search_widget">
                            <form method="GET" action="{% url 'blog:search' %}">
                                <div class="form-group">
                                    <div class="input-group mb-3">
                                        <input name='q' type="text" class="form-control" placeholder='بحث فى المقالات'
                                            onfocus="this.placeholder = ''"
                                            onblur="this.placeholder = 'Search Keyword'">
                                        <div class="input-group-append">
                                            <button class="btn" type="button"><i class="ti-search"></i></button>
                                        </div>
                                    </div>
                                </div>
                                <button class="button rounded-0 primary-bg text-white w-100 btn_1 boxed-btn"
                                    type="submit">إبحث</button>
                            </form>
                        </aside>
                        <aside class="single_sidebar_widget popular_post_widget">
                            <h3 class="widget_title">أقدم المقالات</h3>

                            {% for l_p in last_post %}
                              
                            
                            <div class="media post_item">
                                <img src="{{l_p.post_image.url}}" alt="" style="width: 30spx; height: 30px;">
                                <div class="media-body">
                                    <a href="single-blog.html">
                                        <h3>{{l_p.title}}</h3>
                                    </a>
                                    <p>published at: <span style="color: #00D363;">{{l_p.post_date}}</p>
                                </div>
                            </div>

                            {% endfor %}
                        </aside>
                    </div>
                </div>
                {% for post in search_result %}
                <div class="col-lg-8 mb-5 mb-lg-0" >
                    <div class="blog_left_sidebar" >
                        <article class="blog_item">
                            <div class="blog_item_img">
                                <img class="card-img rounded-0" src="{{post.post_image.url}}" alt="">
                                <a href="#" class="blog_item_date">
                                    <h3>{{post.post_time}}</h3>
                                    <p>{{post.post_day}}</p>
                                </a>
                            </div>

                            <div class="blog_details"> 
                                <a class="d-inline-block" href="">
                                    <h2>{{post.title}}</h2>
                                </a>
                                <p>{{post.content}}</p>
                                <ul class="blog-info-link">
                                    {% for tag in post.tags.all %}
                                    <li><a href="#"><i class="fa fa-user"></i> {{tag}}</a></li>
                                    {% endfor %}
                                    <li><a href="#"><i class="fa fa-comments"></i> 03 Comments</a></li>
                                </ul>
                            </div>
                        </article>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>
    <!--================Blog Area =================-->
</div>
<nav class="blog-pagination justify-content-center d-flex">
    {% if posts.has_other_pages %}
    <ul class="pagination">
        {% if posts.has_previous %}
        <li class="page-item">
            <a href="?page={{ users.previous_page_number }}" class="page-link" aria-label="Previous">
                <i class="ti-angle-right"></i>
            </a>
        </li>
        {% else %}
        <li class="disabled" aria-label="Previous"><</li>
        {% endif %}
        {% for i in posts.paginator.page_range %}
        {% if posts.number == i %}

        <li class="page-item">
            <a href="" class="page-link">{{i}}</a>
        </li>
        {% else %}
        <li class="page-item active">
            <a href="?page={{ i }}" class="page-link">{{i}}</a>
        </li>
        {% endif %}
        {% endfor %}
        {% if posts.has_next %}

        <li class="page-item">
            <a href="?page={{ post.next_page_number }}" class="page-link" aria-label="Next">
                <i class="ti-angle-right"></i>
            </a>
        </li>
        {% else %}
        <li class="disabled" aria-label="Next">></li>
        {% endif %}

    </ul>
    {% endif %}
</nav>
{% endblock body %}

blog/templates/blog/update_post.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{% block body %}
  

<div dir="rtl">
    <!-- Search -->
    <div class="catagory_area ">
<div class="container " style="margin-top: 10rem">
            <div class=" single_text">
                <h2>احجز مع
                    أفضل دكتور في مصر</h3>
                <h3>احجز اونلاين او كلم  ١٧٧٥۸</h4>
                <h4>١٦٠٠٠ دكتور -٤٠٠٠ استاذ واستشاري - اكثر من ۲٠ تخصص</h5>
                <br>
            </div>
            <form  method="GET" action="">
            <div class="row cat_search" >

                <div class="col-lg-3 col-md-4">
                    <div class="single_input">
                        <input type="text" placeholder="إسم الدكتور" >
                    </div>
                </div>

                <div class="col-lg-3 col-md-4">
                    <div class="single_input">
                        <select class="wide" >
                            <option value="" >الموقع</option>
                            <option value="المنصوره">المنصوره</option>
                            <option value="الدقي">الدقي</option>
                            <option value="4">Sylet</option>
                        </select>
                    </div>
                </div>

                <div class="col-lg-3 col-md-4">
                    <div class="single_input">
                        <select class="wide" >
                            <option value="">التخصص</option>
                            <option value="جلدية">جلدية</option>
                            <option value="اسنان">اسنان</option>
                            <option value="نفسي">نفسي</option>
                            <option value="اطفال">اطفال حديثي الولادة</option>
                            <option value="مخ">مخ واعصاب</option>
                            <option value="عظام">عظام</option>
                            <option value="نساء">نساء وتوليد</option>
                            <option value="انف">انف واذن وحنجرة</option>
                            <option value="قلب">قلب واوعية دموية</option>
                            <option value="امراض">امراض دم</option>
                            <option value="اورام">اورام</option>
                            <option value="باطنه">باطنه</option>
                            <option value="تخسيس">تخسيس وتغذية</option>
                            <option value="جاطفال">جراحة اطفال</option>
                            <option value="جاورام">جراحة اورام</option>
                            <option value="جاوعيه">جراحة اوعية دموية</option>
                            <option value="جتجميل">جراحة تجميل</option>
                            <option value="سمنه">جراحه سمنة ومناظير </option>
                            </select>
                    </div>
                </div>

                <div class="col-lg-3 col-md-12">
                    <div class="job_btn">
                        <input type="submit" class="boxed-btn3" value="ابحث هنا">
                    </div>
                </div>

            </div>
            </form> 
        </div>
    </div>
    <!-- endsearch -->

</div>
<!-- bradcam_area  -->

<div dir="rtl">
<div class="container">
    <div class="signup">

    <div class="col-md-9" >
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <h4 class="auth-header">انشاء مدونه جديده</h4>
            {% bootstrap_form postform %}
            <div class="buttons-w"><button type="submit" class="btn btn-success">اضافة</button></div>
            
        </form>
    </div>
    </div>
</div>
</div>

{% endblock body %}