accounts/urls.py
from django.urls import path
from .views import signup,profile
app_name='account'
urlpatterns = [
 path('signup/',signup,name='signup'),
 path('profile/',profile,name='profile'),
]

blog/urls.py
from django.urls import path
from . import views
app_name='blog'
urlpatterns = [
    path('all/',views.blog_list,name='list'),
    path('search/',views.post_search,name='search'),
    path('<int:id>/',views.blog_detail,name='detail'),
    path('new_post/',views.new_post,name='new'),
    path('<int:id>/update',views.update_post,name='update'),
    path('<int:id>/delete',views.delete_post,name='delete'),
    path('<int:id>/like',views.like,name='like'),
    path('<int:id>/likee',views.like_with_ajax,name='ajax')
]

contact/urls.py
from django.urls import path
from .views import contact_info,send
app_name='contact'
urlpatterns = [
    path('',contact_info,name='contact'),
    path('sent/',send,name='sent'),
]

index/urls.py
from django.urls import path
from . import views
app_name='index'
urlpatterns=[
    path('',views.home,name='index'),
    path('search/',views.search_res,name='search'),
    path('home/<str:slug>/',views.detail,name='detail'),
    path('reservation/',views.reservation,name='reservation'),
    path('subscribed_mails/',views.subscribed_mail,name='subscribed'),
    path('my-profile/',views.my_profile,name='profile'),
    path('my-reservation/',views.my_reservtion,name='my_reservation'),
    path('rate/',views.rate,name='rate')
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from froala_editor import views

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('admin/', admin.site.urls),
    path('',include('index.urls',namespace='index')),
    path('blog/',include('blog.urls',namespace='blog')),
    path('froala_editor/',include('froala_editor.urls')),
    path('contact/',include('contact.urls',namespace='contact')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!doctype html>
<html class="no-js" lang="zxx">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">



    <title>Vezeta</title>

    <title>Job Board</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- <link rel="manifest" href="site.webmanifest"> -->
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/logo2.png' %}">
    <link rel="stylesheet" href="{% static 'css/pagination.css">
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Alex+Brush" rel="stylesheet">
    <!-- Place favicon.ico in the root directory -->

    <!-- CSS here -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'css/open-iconic-bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/aos.css' %}">
    <link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.timepicker.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/gijgo.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/slicknav.css' %}">
    <link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <!-- <link rel="stylesheet" href="{% static 'css/responsive.css' %}">  -->
</head>

<body>

<!-- header-start -->
<header>
<div class="header-area ">
    <div id="sticky-header" class="main-header-area">
        <div class="container-fluid " style="background-color: rgba(0, 29, 56, 0.8);" >
            <div class="header_bottom_border">
                <div class="row align-items-center">
                    <div class="col-xl-3 col-lg-2">
                        <div class="logo">
                            <a href="/">
                                <img src="{% static 'img/logo2.png' %}" alt="">
                            </a>
                        </div>
                    </div>
                    <div class="col-xl-6 col-lg-7">
                        <div class="main-menu  d-none d-lg-block">
                            <nav>
                                <ul id="navigation">
                                    {% if request.user.is_authenticated %}
                                        <li><a href="{% url 'index:my_reservation' %}">حجوزاتى</a></li>
                                    {% endif %}
                                    <li><a href="{% url 'index:reservation' %}">احجز دكتورك</a></li>|
                                    <li><a href="{% url 'blog:list' %}">المقالات</a></li>|
                                    <li><a href="{% url 'index:index' %}">الصفحه الرئيسية </a></li>|
                                    <li><a href="{% url 'contact:contact' %}">اتصل بنا</a></li>
                                </ul>
                            </nav>
                        </div>
                    </div>
                    <div class="col-xl-3 col-lg-3 d-none d-lg-block">
                        <div class="Appointment">

                            <div class="phone_num d-none d-xl-block"></div>
                            
                            {% if request.user.is_authenticated %}
                                
                            <div class="d-none d-sm-block">
                                <a class="boxed-btn3" href="">قدم نفسك</a>
                            </div>
                            <div class="d-none d-sm-block">
                                <a class="boxed-btn3" href="{% url 'index:profile' %}">الصفحه الشخصيه</a>
                            </div>
                            <div class="d-none d-sm-block">
                                <a class="boxed-btn3" style="babackground-color: crimson;" href="{% url 'logout' %}">تسجيل خروج</a>
                            </div>
                            {% else %}
                            <div class="phone_num d-none d-xl-block">
                                <a class="boxed-btn3" href="{% url 'login' %}">سجل الدخول</a>
                            </div>
                            <div class="d-none d-lg-block">
                                <a class="boxed-btn3" style="background-color: crimson;" href="{% url 'accounts:signup' %}">التسجيل</a>
                            </div>
                            {% endif %}
                        </div>
                    </div>
                    <div class="col-12">
                        <div class="mobile_menu d-block d-lg-none"></div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
{% if messages %}
<ul class="messages">
   {% for message in messages %}
         <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
   {% endfor %}
</ul>
{% endif %}
</header>
<!-- header-end -->
{% block body %}


{% endblock body %}


<!-- footer start -->
<footer class="footer">
<div class="footer_top">
<div class="container">
    <div class="row">
        <div class="col-xl-3 col-md-6 col-lg-3">
            <div class="footer_widget wow fadeInUp" data-wow-duration="1s" data-wow-delay=".3s">
                <div class="footer_logo">
                    <a href="#">
                        <img src="{% static 'img/logo2.png' %}" alt="">
                    </a>
                </div>
                <p>
                    {{foot.email}} <br>
                    {{foot.phone_number}} <br>
                    {{foot.location}}
                </p>
                <div class="socail_links">
                    <ul>
                        <li>
                            <a href="{{foot.fb_link}}">
                                <i class="ti-facebook"></i>
                            </a>
                        </li>
                        <li>
                            <a href="{{foot.youtube_link}}">
                                <i class="fa fa-youtube"></i>
                            </a>
                        </li>
                        <li>
                            <a href="https://twitter.com/Mahmod_Raouf">
                                <i class="fa fa-twitter"></i>
                            </a>
                        </li>
                        <li>
                            <a href="https://twitter.com/Mahmod_Raouf">
                                <i class="fa fa-instagram"></i>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-xl-2 col-md-6 col-lg-2">
            <div class="footer_widget wow fadeInUp" data-wow-duration="1.1s" data-wow-delay=".4s">
                <h3 class="footer_title">
                    ماذا عنا
                </h3>
                <ul>
                    <li><a href="https://code4learn.teachable.com/p/online-courses">من نحن </a></li>
                    <li><a href="https://code4learn.teachable.com/p/online-courses"> أسعارنا</a></li>
                    <li><a href="https://www.facebook.com/m7modsabra">إستفسار</a></li>
                </ul>

            </div>
        </div>
        <div class="col-xl-3 col-md-6 col-lg-3">
            <div class="footer_widget wow fadeInUp" data-wow-duration="1.2s" data-wow-delay=".5s">
                <h3 class="footer_title">
                    الخدمات
                </h3>
                <ul>
                    <li><a href="https://code4learn.teachable.com/p/soundcloud">اعمالنا</a></li>
                    <li><a href="https://twitter.com/code4learn/status/1236082742582001670?s=21">شركائنا</a></li>
                    <li><a href="https://code4learn.teachable.com/p/online-courses">الخصومات والمشاريع</a></li>
                    <li><a href="https://www.facebook.com/m7modsabra">للإعلان</a></li>
                </ul>
            </div>
        </div>
        <div id='main_subscribe_div' class="col-xl-4 col-md-6 col-lg-4">
            <div class="footer_widget wow fadeInUp" data-wow-duration="1.3s" data-wow-delay=".6s">
                <h3 class="footer_title">
                    Subscribe
                </h3>
                <form action="{% url 'index:index' %}" id="subscribe_form" class="newsletter_form" method="POST">
                    {% csrf_token %}
                    <input type="text" placeholder="Enter your mail" name='email1'>
                    <button type="submit">Subscribe</button>
                </form>
                <p class="newsletter_text">Esteem spirit temper too say adieus who direct esteem esteems
                    luckily.</p>
            </div>
        </div>
        <div id="success" style="display:none;" class="col-xl-4 col-md-6 col-lg-4">
            <div class="footer_widget wow fadeInUp" data-wow-duration="1.3s" data-wow-delay=".6s">
                <h3 class="footer_title">
                    subscribed successfully
                </h3>
    </div>
</div>
</div>
<div class="copy-right_text wow fadeInUp" data-wow-duration="1.4s" data-wow-delay=".3s">
<div class="container">
    <div class="footer_border"></div>
    <div class="row">
        <div class="col-xl-12">
            <p class="copy_right text-center">
                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            </p>
        </div>
    </div>
</div>
</div>
</footer>
<!--/ footer end  -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script>
    $('#subscribe_form').submit(function(e){
        e.preventDefault();
        var form = $(this);
        var url = form.attr('action');
    $.ajax ({
        type:'POST',
        url:url,
        data:form.serialize(),
        success: function (data){
            document.getElementById('main_subscribe_div').style.display='none';
            document.getElementById('success').style.display='block';
            }
        })
    } )
</script>

<!-- link that opens popup -->
<!-- JS here -->
<script src="{% static 'js/vendor/modernizr-3.5.0.min.js' %}"></script>
<script src="{% static 'js/vendor/jquery-1.12.4.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/isotope.pkgd.min.js' %}"></script>
<script src="{% static 'js/bootstrap-datepicker.js' %}"></script>
<script src="{% static 'js/ajax-form.js' %}"></script>
<script src="{% static 'js/waypoints.min.js' %}"></script>
<script src="{% static 'js/jquery.counterup.min.js' %}"></script>
<script src="{% static 'js/imagesloaded.pkgd.min.js' %}"></script>
<script src="{% static 'js/scrollIt.js' %}"></script>
<script src="{% static 'js/jquery.scrollUp.min.js' %}"></script>
<script src="{% static 'js/wow.min.js' %}"></script>
<script src="{% static 'js/nice-select.min.js' %}"></script>
<script src="{% static 'js/jquery.slicknav.min.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/plugins.js' %}"></script>
<script src="{% static 'js/gijgo.min.js' %}"></script>
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="{% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>
<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'js/jquery.stellar.min.js' %}"></script>
<script src="{% static 'js/aos.js' %}"></script>
<script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>
<script src="{% static 'js/bootstrap-datepicker.js' %}"></script>
<!-- <script src="{% static 'js/jquery.timepicker.min.js' %}"></script> -->
<script src="{% static 'js/scrollax.min.js' %}"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
<script src="{% static 'js/google-map.js' %}"></script>



<!--contact js-->
<script src="js/contact.js"></script>
<script src="js/jquery.ajaxchimp.min.js"></script>
<script src="js/jquery.form.js"></script>
<script src="js/jquery.validate.min.js"></script>
<script src="js/mail-script.js"></script>


<script src="js/main.js"></script>
</body>

</html>

templates/search.html
    <!-- Search -->
    <div class="catagory_area ">
<div class="container " style="margin-top: 10rem">
            <div class=" single_text">
                <h3>احجز مع
                    أفضل دكتور في مصر</h3>
                <h4>احجز اونلاين او كلم  ١٧٧٥۸</h4>
                <h5>١٦٠٠٠ دكتور -٤٠٠٠ استاذ واستشاري - اكثر من ۲٠ تخصص</h5>
                <br>
            </div>
            <form  method="GET" action="{% url 'index:search' %}">
            <div class="row cat_search" >

                <div class="col-lg-3 col-md-4">
                    <div class="single_input">
                        <input type="text" placeholder="إسم الدكتور" name="name" >
                    </div>
                </div>

                <div class="col-lg-3 col-md-4">
                    <div class="single_input">
                        <select class="wide" name="loc">
                            <option value="" >الموقع</option>
                            {% for ad in address %}
                            <option value="{{ad}}">{{ad}}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>

                <div class="col-lg-3 col-md-4">
                    <div class="single_input">
                        <select class="wide" name='spec'>
                            <option value="">التخصص</option>
                            {% for category in categories %}
                            <option value="{{category.speialists}}">{{category.speialists}}</option>
                            {% endfor %}
                            </select>
                    </div>
                </div>

                <div class="col-lg-3 col-md-12">
                    <div class="job_btn">
                        <input type="submit" class="boxed-btn3" value="ابحث هنا">
                    </div>
                </div>

            </div>
            </form>
        </div>
    </div>
    <!-- endsearch -->