blog/urls.py
from django.urls import path
from . import views
app_name='blog'
urlpatterns = [
    path('all/',views.blog_list,name='list'),
    path('search/',views.post_search,name='search'),
    path('<int:id>/',views.blog_detail,name='detail'),
    path('new_post/',views.new_post,name='new'),
    path('<int:id>/update',views.update_post,name='update'),
    path('<int:id>/delete',views.delete_post,name='delete'),
    path('<int:id>/like',views.like,name='like'),
    path('<int:id>/likee',views.like_with_ajax,name='ajax')
]

contact/urls.py
from django.urls import path
from .views import contact_info,send
app_name='contact'
urlpatterns = [
    path('',contact_info,name='contact'),
    path('sent/',send,name='sent'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from froala_editor import views

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('admin/', admin.site.urls),
    path('',include('index.urls',namespace='index')),
    path('blog/',include('blog.urls',namespace='blog')),
    path('froala_editor/',include('froala_editor.urls')),
    path('contact/',include('contact.urls',namespace='contact')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contact/models.py
from django.db import models

# Create your models here.

contact/views.py
from django.shortcuts import render,redirect
from django.core.mail import send_mail
# Create your views here.
def contact_info(request):
    return render(request,'contact/contact.html')
def send(request):
    if request.method=='POST':
        name=request.POST.get('name')
        print(name)
        mail =request.POST.get('mail')
        print(mail)
        subject=request.POST.get('subject')
        print(subject)
        messages=request.POST.get('messages')
        print(messages)
        send_mail(
            subject,
            f'sender name{name},sender mail{mail},subject{subject},message{messages}',
            mail,
            ['eng_mina_hosam@yahoo.com'],
            fail_silently=False,
        )
        return redirect('contact:contact')

contact/templates/contact/contact.html
{%extends 'base.html'%}
{% load static %}
{% load bootstrap4 %}
{% block body %}

		<section class="ftco-section contact-section ftco-degree-bg">
      <div class="container">
        <div class="row d-flex mb-5 contact-info">
          <div class="col-md-12 mb-4">
            <h4 class="h4">Contact Information</h4>
          </div>
          <div class="w-100"></div>
          <div class="col-md-3">
            <p><span>Address:</span> {{foot.location}}</p>
          </div>
          <div class="col-md-3">
            <p><span>Phone:</span> <a href="tel://{{foot.phone_number}}">{{foot.phone_number}}</a></p>
          </div>
          <div class="col-md-3">
            <p><span>Email:</span> <a href="mailto:{{foot.email}}">{{foot.email}}</a></p>
          </div>
          <div class="col-md-3">
            <p><span>Website</span> <a href="/">vezeeta</a></p>
          </div>
        </div>
        <div class="row block-9">
          <div class="col-md-6 pr-md-5">
            <form method="POST" action="{% url 'contact:sent' %}">
              {% csrf_token %}
              <div class="form-group">
                <input type="text" class="form-control" name="name" placeholder="Your Name">
              </div>
              <div class="form-group">
                <input type="text" class="form-control" name="mail" placeholder="Your Email">
              </div>
              <div class="form-group">
                <input type="text" class="form-control" name="subject" placeholder="Subject">
              </div>
              <div class="form-group">
                <textarea name="messages" id="" cols="30" rows="7" class="form-control" placeholder="Message"></textarea>
              </div>
              <div class="form-group">
                <input type="submit" value="Send Message" class="btn btn-primary py-3 px-5">
              </div>
            </form>
          
          </div>

          <div class="col-md-6" id="map"></div>
        </div>
      </div>
    </section>

{% endblock body%}
    