blog/urls.py
from django.urls import path
from . import views
app_name='blog'
urlpatterns = [
    path('all/',views.blog_list,name='list'),
    path('search/',views.post_search,name='search'),
    path('<int:id>/',views.blog_detail,name='detail'),
    path('new_post/',views.new_post,name='new'),
    path('<int:id>/update',views.update_post,name='update'),
    path('<int:id>/delete',views.delete_post,name='delete'),
    path('<int:id>/like',views.like,name='like'),
    path('<int:id>/likee',views.like_with_ajax,name='ajax')
]

index/urls.py
from django.urls import path
from . import views
app_name='index'
urlpatterns=[
    path('',views.home,name='index'),
    path('search/',views.search_res,name='search'),
    path('home/<str:slug>/',views.detail,name='detail'),
    path('reservation/',views.reservation,name='reservation'),
    path('subscribed_mails/',views.subscribed_mail,name='subscribed'),
    path('my-profile/',views.my_profile,name='profile'),
    path('my-reservation/',views.my_reservtion,name='my_reservation'),
    path('rate/',views.rate,name='rate')
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from froala_editor import views

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('admin/', admin.site.urls),
    path('',include('index.urls',namespace='index')),
    path('blog/',include('blog.urls',namespace='blog')),
    path('froala_editor/',include('froala_editor.urls')),
    path('contact/',include('contact.urls',namespace='contact')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

index/templates/home/detail.html
{% extends "base.html" %}
{% load static %}
{% block body %}
  

<div dir="rtl">
    <!-- Search -->
    {% include "home/search.html" %}
    <!-- endsearch -->

<div class="job_details_area">
<div class="container">
    <div class="row">
        <div class="col-lg-8">
            <div class="job_details_header">
                <div class="single_jobs white-bg d-flex justify-content-between">
                    <div class="jobs_left d-flex align-items-center">
                        <div >
                            
                                <img class="img-circle" src="{{doctor.doctor_image.url}}" alt="" width="100" height="100">
                            
                        </div>
                        <div class="jobs_conetent">
                            <a href="#" ><h4>{{doctor.name}}</h4></a>
                            <div class="links_locat d-flex align-items-center">
                                <div class="location">
                                    <p> <i class="fa fa-map-marker"></i> {{doctor.address}}</p>
                                </div>
                                <div class="location">
                                    <p> <i class="fa fa-clock-o"></i>  {{doctor.waiting_time}}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="jobs_right">
                        <div class="apply_now">
                            <a class="boxed-btn3" href="">حجز كشف</a>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="descript_wrap white-bg">
                <div class="single_wrapp">
                    <h3>نبذه عن الدكتور</h3>
                </div>
                <div class="white-card white-card-inner">
                    <div class="single_wrap" style="margin-top: 10px;">
                        <h4>{{doctor.description}}</h4>
                        <ul>
                            <p>وصف الدكتور</p>
                        </ul>
                    </div>
                </div>
                <div class="single_wrap">
                    <h4>خدمات الدكتور :</h4>
                    <ul>
                        <p class="tagitem disable-click pull-left mr-4" style="background-color: #f5f5f5;
                        color: #808184;"> {{doctor.specialist_doctor}} 
                        </p>
                    </ul>
                    <br>
                </div>
                <div class="single_wrap">
                    <h4>صور العيادة :</h4>
                            <img class="image_clinic" src="{% static 'img/candiateds/2.png' %}" alt="" >
                            <img class="image_clinic" src="{% static 'img/candiateds/2.png' %}" alt="" >
                            <img class="image_clinic" src="{% static 'img/candiateds/2.png' %}" alt="" >
                    


                </div>
            </div>
            <div class="col text-left mt-3">
                <form class="rate-form" id='{{doctor.id}}' method="GET" action="">
                    <!-- to make image category for clinic image -->
                    <a href="{% url 'index:rate' %}"><button class="fa fa-star my-btn checked" id="first"></button></a>
                    <a href="{% url 'index:rate' %}"><button class="fa fa-star my-btn" id="second"></button></a>
                    <a href="{% url 'index:rate' %}"><button class="fa fa-star my-btn" id="third"></button></a>
                    <a href="{% url 'index:rate' %}"><button class="fa fa-star my-btn" id="fourth"></button></a>
                    <a href="{% url 'index:rate' %}"><button class="fa fa-star my-btn" id="fifth"></button></a>
                </form>
                <div class="col text-right">
                    <h2>تقييم الدكتور</h2>
                </div>
            </div>
    <!-- comments -->
    <div class="section-row">
        <div class="section-title">
            <h2 style="color: brown;">التعليقات (  )</h2>
        </div>

        <div class="post-comments" >

            <!-- comment -->
            <div class="media">
                <div class="media-left">
                    <img class="media-object" src="{% static 'img/avatar.jpg' %}" alt="">
                </div>
                <div class="media-body " >
                    <div class="media-heading">
                        <h4>اسم الكاتب</h4>
                        <span class="time">تم التعليق في </span>
                    </div>
                    <p>الكومنتات</p>
                    <a href="#" class="reply">الردود ..</a>

                    <!-- comment -->
                    <div class="media">
                        <div class="media-left">
                            <img class="media-object" src="" alt="">
                        </div>
                        <div class="media-body">
                            <div class="media-heading">
                                <h4>محمود عبد الرؤف صبره</h4>
                                <span class="time">تم التعليق فى </span>
                            </div>
                            <p>شكرا جدا واتمنى ان تتصفح باقي المواضيع .....</p>
                        </div>
                    </div>
                    <!-- /comment -->
                </div>
            </div>
            <!-- /comment -->

            <div class="media-heading">
                <h4>لا يوجد تعليقات حتى الأن ..</h4>
            </div>

        </div>
    </div>
    <!-- /comments -->                    
    <div class="apply_job_form white-bg">
        <h4>إترك تعليقك</h4>
        <form method="POST" >

            <div class="row">
                <div class="col-md-6">
                    <div class="input_field">
                        <input type="text"  placeholder=" الإسم">
                        
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="input_field">
                        <input type="text"  placeholder=" الإيميل">
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="input_field">
                        <textarea  cols="30" rows="10" placeholder="تعليقك .."></textarea>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="submit_btn">
                        <button class="boxed-btn3 w-100" type="submit">تعليق</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
        </div>
        <div class="col-lg-4">
            <div class="job_sumary">
                <div class="summery_header">
                    <h3>معلومات عن الدكتور </h3>
                </div>
                <div class="job_content">
                    <ul>
                        <li>  انضم إلينا : <span style="color: blue;"></span></li>
                        <li> الكشف : <span style="color: blue;"> جنية</span></li>
                        <li> رقم الهاتف  : <span style="color: blue;"></span></li>
                        <li>عدد ساعات العمل : <span style="color: blue;"> ساعات</span></li>
                    </ul>
                    
                </div>
            </div>
            <div class="share_wrap d-flex">
                <span>شارك الصفحه :</span>
                <ul>
                    <li><a href=""> <i class="fa fa-facebook"></i></a> </li>
                    <li><a href=""> <i class="fa fa-google-plus"></i></a> </li>
                    <li><a href=""> <i class="fa fa-twitter"></i></a> </li>
                    <li><a href=""> <i class="fa fa-envelope"></i></a> </li>
                </ul>
            </div>
            <div class="job_location_wrap">
                <div class="job_lok_inner">
                    <div id="map" style="height: 200px;"></div>
                    <script>
                        function initMap() {
                        var uluru = {lat: -25.363, lng: 131.044};
                        var grayStyles = [
                            {
                            featureType: "all",
                            stylers: [
                                { saturation: -90 },
                                { lightness: 50 }
                            ]
                            },
                            {elementType: 'labels.text.fill', stylers: [{color: '#ccdee9'}]}
                        ];
                        var map = new google.maps.Map(document.getElementById('map'), {
                            center: {lat: -31.197, lng: 150.744},
                            zoom: 9,
                            styles: grayStyles,
                            scrollwheel:  false
                        });
                        }
                        
                    </script>
                    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDpfS1oRGreGSBU5HHjMmQ3o5NLw7VdJ6I&callback=initMap"></script>
                    
                    </div>
            </div>
        </div>
    </div>
</div>
</div>
</div>
<script>
    const one = document.getElementById('first')
    const two = document.getElementById('second')
    const three = document.getElementById('third')
    const four = document.getElementById('fourth')
    const five = document.getElementById('fifth')
    console.log(five)
    const rateform=document.querySelector('.rate-form')
    const handleselector = (selection)=>{
        switch(selection){
            case 'first':{
                one.classList.add('checked')
                two.classList.remove('checked')
                three.classList.remove('checked')
                four.classList.remove('checked')
                five.classList.remove('checked')
                return
            };
            case 'second':{
                one.classList.add('checked')
                two.classList.add('checked')
                three.classList.remove('checked')
                four.classList.remove('checked')
                five.classList.remove('checked')
                return
            };
            case 'third':{
                one.classList.add('checked')
                two.classList.add('checked')
                three.classList.add('checked')
                four.classList.remove('checked')
                five.classList.remove('checked')
                return
            };
            case 'fourth':{
                one.classList.add('checked')
                two.classList.add('checked')
                three.classList.add('checked')
                four.classList.add('checked')
                five.classList.remove('checked')
                return
            };
            case 'fifth':{
                one.classList.add('checked')
                two.classList.add('checked')
                three.classList.add('checked')
                four.classList.add('checked')
                five.classList.add('checked')
                return
            }
        }
    }
    const numvalue = (stringvalue)=>{
        let val;
        if(stringvalue === 'first'){
            val = 1
        }
        else if(stringvalue === 'second'){
            val=2
        }
        else if(stringvalue === 'third'){
            val=3
        }
        else if(stringvalue === 'fourth'){
            val=4
        }
        else if(stringvalue === 'fifth'){
            val=5
        }
        else{
            val = 0
        }
        return val
    }
    const arr=[one,two,three,four,five] 
    arr.forEach(item=>item.addEventListener('mouseover',(event)=>{
        handleselector(event.target.id)
    }))
    arr.forEach(item=>addEventListener('click',(event)=>{
        const value = event.target.id
        console.log(value)
        rateform.addEventListener('submit',e =>{
            e.preventDefault()
            const id = e.target.id
            console.log(id)
            const numericvalue=numvalue(value)
            console.log(numericvalue)
            $.ajax({
                type:'GET',
                url:'/rate/',
                data : {
                    doctor_id:id,
                    score_id:numericvalue
                },
                success :function(response){
                    console.log(response)
                },
                error:function(response){
                    console.log(response)
                }
            })
        })
    }))
</script>
{% endblock body %}

index/templates/home/index.html
{% extends 'base.html' %}
{% load static %}
{% block body %}

<div dir="rtl">
    {% include 'home/search.html' %}
    <!-- job_listing_area_start  -->
    <!-- Flexbox container for aligning the toasts -->
    {% for doctor in doctors %}
    <div class="job_listing_area">
        <div class="container">

            <div class="job_lists">
                <div class="row">
                    <div class="col-lg-10 col-md-10" style="height: 16rem;">
                        <div class="single_jobs white-bg d-flex justify-content-between">
                            <div class="jobs_left d-flex align-items-center">
                                <div>

                                    <img src="{{doctor.doctor_image.url}}" alt="" width="100" height="100">

                                </div>
                                <div class="jobs_conetent">
                                    <a href="{% url 'index:detail' doctor.slug %}">
                                        <h5>دكتور{{doctor.name}} </h5>
                                    </a>
                                    <h6>subtitle</h6>

                                    <div class="links_locat">
                                        <div class="location">
                                            <p> <i class="fas fa-briefcase-medical"></i> دكتور <span
                                                    style="color: blue;">doctor</span> متخصص في <span
                                                    style="color: blue;">{{doctor.specialist_doctor.speialists}}</span>
                                            </p>
                                            <p> <i class="fa fa-map-marker"></i>{{doctor.address}}</p>
                                            <p> <i class="fa fa-map-marker"></i> الكشف : <span
                                                    style="color: blue;">{{doctor.price}}</span> جنية</p>
                                            <p> <i class="fa fa-clock-o"></i> مدة الانتظار : <span
                                                    style="color: blue;">{{doctor.waiting_time}}</span> ساعه</p>
                                            <p> <i class="fa fa-clock-o"></i> عدد ساعات العمل : <span
                                                    style="color: blue;">{{doctor.opening_hours}}</span> ساعه</p>
                                            <p> <i class="fa fa-clock-o"></i>سعر المكالمه العادية :<span
                                                    style="color: blue;"> {{doctor.phone_number}} </span> </p>


                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="jobs_right">
                                <div class="apply_now">
                                    <a class="boxed-btn3" href="{% url 'index:reservation' %}">حجز كشف</a>
                                </div>

                                <!-- <div class="rating">
                                    <form class="rate-form">
                                        <!-- to make image category for clinic image -->

                                        {% if doctor.doctor_rate == rate %}
                                        <h3>not rated until now</h3>
                                            <button class="fa fa-star my-btn"></button>
                                            <button class="fa fa-star my-btn"></button>
                                            <button class="fa fa-star my-btn"></button>
                                            <button class="fa fa-star my-btn"></button>
                                            <button class="fa fa-star my-btn"></button>
                                        {% elif doctor.doctor_rate == rate  %}
                                            <button class="fa fa-star my-btn checked"></button>
                                            <button class="fa fa-star my-btn"></button>
                                            <button class="fa fa-star my-btn"></button>
                                            <button class="fa fa-star my-btn"></button>
                                            <button class="fa fa-star my-btn"></button>
                                        {% elif doctor.doctor_rate == rate %}
                                            <button class="fa fa-star my-btn checked"></button>
                                            <button class="fa fa-star my-btn checked"></button>
                                            <button class="fa fa-star my-btn"></button>
                                            <button class="fa fa-star my-btn"></button>
                                            <button class="fa fa-star my-btn"></button>
                                        {% elif doctor.doctor_rate == 3 %}
                                            <button class="fa fa-star my-btn checked"></button>
                                            <button class="fa fa-star my-btn checked"></button>
                                            <button class="fa fa-star my-btn"></button>
                                            <button class="fa fa-star my-btn"></button>
                                            <button class="fa fa-star my-btn"></button>
                                        {% elif doctor.doctor_rate == 4 %}
                                            <button class="fa fa-star my-btn checked"></button>
                                            <button class="fa fa-star my-btn checked"></button>
                                            <button class="fa fa-star my-btn checked"></button>
                                            <button class="fa fa-star my-btn checked"></button>
                                            <button class="fa fa-star my-btn"></button>
                                        {% elif doctor.doctor_rate == 5 %}
                                            <button class="fa fa-star my-btn checked"></button>
                                            <button class="fa fa-star my-btn checked"></button>
                                            <button class="fa fa-star my-btn checked"></button>
                                            <button class="fa fa-star my-btn checked"></button>
                                            <button class="fa fa-star my-btn checked"></button>
                                        {% endif %}
                                    </form>
                                    <div class="rating">
                                        <h5>تقييم الدكتور</h5>
                                    </div>
                                </div> -->
                            </div>

                        </div>
                    </div>


                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <!-- job_listing_area_end  -->
</div>
<!-- featured_candidates_area_start  -->
<div class="featured_candidates_area">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="section_title text-center mb-40">
                    <h3>المرشحين المميزين</h3>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="candidate_active owl-carousel">
                    <div class="single_candidates text-center">
                        <div class="thumb">
                            <img class="img-circle " src="{% static 'img/candiateds/2.png' %}" alt="">

                        </div>
                        <a href="">
                            <h4>الاسم</h4>
                        </a>
                        <p> التخصص</p>
                        <div class="best-rating">
                            <div class="text-warning">
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>

                            </div>
                            <div class="best-rating">
                                <h5>تقييم الدكتور</h5>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
<nav aria-label="Page navigation example">
    {% if doctors.has_other_pages %}
    <ul class="pagination" style="margin-left:600px  !important;">
        {% if doctors.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ users.previous_page_number }}" aria-label="Previous">
                Previous
            </a>
        </li>
        {% else %}
        <li class="disabled" aria-label="Previous">Previous</li>
        {% endif %}
        {% for i in doctors.paginator.page_range %}
        {% if doctors.number == i %}
        <li class="page-item"><a class="page-link" href="#">{{i}}</a></li>
        {% else %}
        <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
        {% endif %}
        {% endfor %}
        {% if doctors.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ doctors.next_page_number }}" aria-label="Next">
                Next
            </a>
        </li>
        {% else %}
        <li class="disabled" aria-label="Next">Next</li>
        {% endif %}
    </ul>
    {% endif %}
</nav>
<!-- featured_candidates_area_end  -->

{% endblock body %}

index/templates/home/my_reservation.html
{% extends 'base.html' %}
{% load static %}
{% block body %}

<div dir="rtl">
    {% include 'home/search.html' %}
    <!-- job_listing_area_start  -->
    <!-- Flexbox container for aligning the toasts -->
    {% for doctor in doctors %}
    <!-- {{doctor.doctor_name.doctor_image.url}} -->
    <div class="job_listing_area">
        <div class="container">

            <div class="job_lists">
                <div class="row">
                    <div class="col-lg-10 col-md-10" style="height: 16rem;">
                        <div class="single_jobs white-bg d-flex justify-content-between">
                            <div class="jobs_left d-flex align-items-center">
                                <div>

                                    <img src="{{doctor.doctor_name.doctor_image.url}}" alt="" width="100" height="100">

                                </div>
                                <div class="jobs_conetent">
                                    <a href="{% url 'index:detail' doctor.doctor_name.slug %}">
                                        <h5>دكتور{{doctor.doctor_name.name}} </h5>
                                    </a>
                                    <h6>subtitle</h6>

                                    <div class="links_locat">
                                        <div class="location">
                                            <p> <i class="fas fa-briefcase-medical"></i> دكتور <span
                                                    style="color: blue;">doctor</span> متخصص في <span
                                                    style="color: blue;">{{doctor.doctor_name.specialist_doctor.speialists}}</span>
                                            </p>
                                            <p> <i class="fa fa-map-marker"></i>{{doctor.doctor_name.address}}</p>
                                            <p> <i class="fa fa-map-marker"></i> الكشف : <span
                                                    style="color: blue;">{{doctor.doctor_name.price}}</span> جنية</p>
                                            <p> <i class="fa fa-map-marker"></i> يوم الكشف : <span
                                                    style="color: blue;">{{doctor.date_reservation1}}</span> يوم</p>
                                            <p> <i class="fa fa-map-marker"></i> ميعاد الكشف : <span
                                                    style="color: blue;">{{doctor.time_reservation}}</span> يوم</p>
                                            <p> <i class="fa fa-clock-o"></i> مدة الانتظار : <span
                                                    style="color: blue;">{{doctor.doctor_name.waiting_time}}</span> ساعه</p>
                                            <p> <i class="fa fa-clock-o"></i> عدد ساعات العمل : <span
                                                    style="color: blue;">{{doctor.doctor_name.opening_hours}}</span> ساعه</p>
                                            <p> <i class="fa fa-clock-o"></i>سعر المكالمه العادية :<span
                                                    style="color: blue;"> {{doctor.doctor_name.phone_number}} </span> </p>


                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="jobs_right">
                                <div class="apply_now">
                                    <a class="boxed-btn3" href="{% url 'index:reservation' %}">حجز كشف</a>
                                </div>

                                <div class="rating">
                                    <div class="text-warning">
                                        <!-- to make image category for clinic image -->
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                    </div>
                                    <div class="rating">
                                        <h5>تقييم الدكتور</h5>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>


                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <!-- job_listing_area_end  -->
</div>
<!-- featured_candidates_area_start  -->
<div class="featured_candidates_area">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="section_title text-center mb-40">
                    <h3>المرشحين المميزين</h3>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="candidate_active owl-carousel">
                    <div class="single_candidates text-center">
                        <div class="thumb">
                            <img class="img-circle " src="{% static 'img/candiateds/2.png' %}" alt="">

                        </div>
                        <a href="">
                            <h4>الاسم</h4>
                        </a>
                        <p> التخصص</p>
                        <div class="best-rating">
                            <div class="text-warning">
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>

                            </div>
                            <div class="best-rating">
                                <h5>تقييم الدكتور</h5>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
<nav aria-label="Page navigation example">
    {% if doctors.has_other_pages %}
    <ul class="pagination" style="margin-left:600px  !important;">
        {% if doctors.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ users.previous_page_number }}" aria-label="Previous">
                Previous
            </a>
        </li>
        {% else %}
        <li class="disabled" aria-label="Previous">Previous</li>
        {% endif %}
        {% for i in doctors.paginator.page_range %}
            {% if doctors.number == i %}
                <li class="page-item"><a class="page-link" href="#">{{i}}</a></li>
            {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
        {% endfor %}
        {% if doctors.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ doctors.next_page_number }}" aria-label="Next">
                Next
            </a>
        </li>
        {% else %}
        <li class="disabled" aria-label="Next">Next</li>
        {% endif %}
    </ul>
    {% endif %}
</nav>
<!-- featured_candidates_area_end  -->

{% endblock body %}